name = "chs1970"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "chs1970-db"
database_id = "1ab2e741-b12b-47d8-becf-fc2f57a34b86"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "chs1970-assets"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "chs1970-db"
database_id = "1ab2e741-b12b-47d8-becf-fc2f57a34b86"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "chs1970-assets"